# Generated by Django 6.0.2 on 2026-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('service_category', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('experience_year', models.IntegerField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('total_jobs', models.IntegerField()),
                ('availability_status', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
