# Generated by Django 6.0.2 on 2026-03-09 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='city',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline')], default='Available', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='city_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='services.city'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='services.serviceprovider')),
            ],
        ),
    ]
