# Generated by Django 6.0.2 on 2026-03-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service'),
        ('services', '0002_serviceprovider_remove_service_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
