# Generated by Django 6.0.2 on 2026-03-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_address_service_area_service_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service')),
            ],
        ),
    ]
