# Generated by Django 6.0.2 on 2026-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='portfolio_images',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
