# Generated by Django 6.0.2 on 2026-03-12 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_portfolio_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='services.category'),
        ),
    ]
