# Generated by Django 6.0.2 on 2026-03-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_service'),
        ('services', '0005_serviceimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service'),
            preserve_default=False,
        ),
    ]
