# Generated by Django 6.0.2 on 2026-03-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_customer_booking_user_remove_booking_timeslot_and_more'),
        ('reviews', '0003_rename_customer_review_user_remove_review_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_details', to='bookings.booking'),
        ),
    ]
