# Generated by Django 6.0.2 on 2026-03-10 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_customer_booking_user_remove_booking_timeslot_and_more'),
        ('tasks', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tasks.task'),
        ),
    ]
