# Generated by Django 6.0.2 on 2026-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_method_alter_booking_booking_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending payment', 'Pending Payment')], default='pending', max_length=20),
        ),
    ]
